GET http://localhost:5001/api/v1/user

###
GET http://localhost:5001/api/v1/user/64921b25dc25ab24d011203a

###
POST http://localhost:5001/api/v1/user
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@bamoh.com",
  "password": "testtest"
}

###
PUT http://localhost:5001/api/v1/user/649216b8847b2b6b49981970
Content-Type: application/json

{
  "firstName": "Momed",
  "lastName": "Ba"
}

###
DELETE http://localhost:5001/api/v1/user/649216a4847b2b6b4998196f